### ISSUE TITLE
R CMD check HMMextra0s fails on Mahuika

### ISSUE THREAD

**Issue by athenatingwang** [athenatingwang/HMMextra0s#11]
I tried to use R CMD check HMMextra0s to check and then build the package on Mahuika, but it didn't work. I got an error related to sig variable (see below). 

Running examples in ‘HMMextra0s-Ex.R’ failed
The error most likely occurred in:

> ### Name: Viterbi.hmm0norm2d
> ### Title: Viterbi Path of a Bivariate HMM with Extra Zeros
> ### Aliases: Viterbi.hmm0norm2d
> ### Keywords: inversion
>
> ### ** Examples
>
> pie <- c(0.002,0.2,0.4)
> gamma <- matrix(c(0.99,0.007,0.003,
+                   0.02,0.97,0.01,
+                   0.04,0.01,0.95),byrow=TRUE, nrow=3)
> mu <- matrix(c(35.03,137.01,
+                35.01,137.29,
+                35.15,137.39),byrow=TRUE,nrow=3)
> sig <- array(NA,dim=c(2,2,3))
> sig[,,1] <- matrix(c(0.005, -0.001,
+                    -0.001,0.01),byrow=TRUE,nrow=2)
> sig[,,2] <- matrix(c(0.0007,-0.0002,
+                     -0.0002,0.0006),byrow=TRUE,nrow=2)
> sig[,,3] <- matrix(c(0.002,0.0018,
+                      0.0018,0.003),byrow=TRUE,nrow=2)
> delta <- c(1,0,0)
> y <- sim.hmm0norm2d(mu,sig,pie,gamma,delta, nsim=5000)
> R <- y$x
> Z <- y$z
> HMMEST <- hmm0norm2d(R, Z, pie, gamma, mu, sig, delta)
Error in dmvnorm(R, mean = mu[k, ], sigma = sig[, , k]) :
  sigma must be a symmetric matrix
Calls: hmm0norm2d -> dmvnorm
Execution halted
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  pdflatex is not available
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  pdflatex is not available
Error in running tools::texi2pdf()
You may want to clean up by 'rm -Rf /tmp/RtmphZpVWT/Rd2pdf9b9a57c48759'
* DONE

**Comment by tinyendian** [comment]
After some investigation, it turned out that small numerical differences between the Fortran and R code caused this problem.

In the 2D version of the model, full variance-covariance matrices "hatsig" are computed in "M-step" as follows:

```
            for (kk in 1:n) {
                for (jj in 1:n) {
                    hatsig[kk,jj,j] <- ( sum( v[Z==1,j] * ( R[Z==1,kk] - hatmu[j,kk] )*
                                       ( R[Z==1,jj] - hatmu[j,jj] ) ) /
                                         sum( v[Z==1,j] ) )
                }
            }
```
Each matrix ```hatsig[,,j]``` must be symmetric by definition. While the R code seems to produce exactly symmetric matrices, the Fortran code can sometimes produce slight asymmetries which are then picked up by R function ```dmvnorm``` and result in the ```sigma must be a symmetric matrix``` error message shown above.

The solution for this issue is to compute only the lower or upper triangular and copy covariances to create an exactly symmetric matrix. This will also improve performance as computing a full symmetric matrix leads to redundant work.

**Comment by tinyendian** [comment]
Created a pull request with a fix for this problem.

**Comment by athenatingwang** [comment]
Thank you for sorting this out. I have merged the pull request.
